###############################################################
# Program:
#     Week 01, Vector
#     Brother JonesL, CS235
# Author:
#     Makram Ibrahim
# Summary:
#     This program is to demonstrate the Vector class with different 
#     vector member functions. It helps the client to use a such convenient
#     to add any items to the vectors and pull whatever data from it.
# 
# Time:
#     It took me more than 17 hours to finish this assignment. 
#     I had a very hard time to pass the test 3 and 4. However,
#     after going back to textbook, it helped me a lot to understand 
#     vector's concept and push_back method where I was struggling. 
###############################################################

##############################################################
# The main rule
##############################################################
a.out: vector.h week01.o
	g++ -o a.out week01.o 
	tar -cf week01.tar vector.h week01.cpp makefile

##############################################################
# The individual components
#      week01.o     : the driver program
##############################################################
week01.o: vector.h week01.cpp
	g++ -c week01.cpp
